import {
  AgentOperation,
  ActivityItem,
  AttentionItem,
  DashboardMetrics,
} from '@/types/dashboard';

export const mockDashboardMetrics: DashboardMetrics = {
  activeAgentsCount: 12,
  needsAttentionCount: 3,
  successRatePercent: 94.7,
  totalRunsCount: 24473,
  totalTokensProcessed: '18.4M',
  systemStatus: 'All Systems OK',
  notificationsCount: 3,
  userName: 'Arijeet',
};

export const mockAgentOperations: AgentOperation[] = [
  {
    id: 'agent-1',
    name: 'Competitor Monitor',
    codename: 'AERO-BROWSER-01',
    category: 'Browser',
    status: 'running',
    runtime: '02:14',
    tasksCount: 9345,
    successRate: 98.62,
    progressPercent: 78,
    model: 'Claude 3.7 Sonnet',
    lastAction: 'Extracting SaaS tier pricing matrices and feature diffs',
    latencyMs: 142,
    tokensUsed: '4.2M',
    cost: '$14.20',
    chartData: [45, 52, 58, 65, 62, 78, 85, 92, 98.6],
    deltaRate: '+6.25%',
    deltaPositive: true,
  },
  {
    id: 'agent-2',
    name: 'Lead Researcher',
    codename: 'SYNTH-DISCOVERY-02',
    category: 'Research',
    status: 'running',
    runtime: '00:48',
    tasksCount: 12345,
    successRate: 94.72,
    progressPercent: 64,
    model: 'Gemini 2.5 Pro',
    lastAction: 'Synthesizing verified executive contact intelligence',
    latencyMs: 198,
    tokensUsed: '6.8M',
    cost: '$18.90',
    chartData: [40, 48, 55, 62, 70, 75, 84, 88, 94.7],
    deltaRate: '+5.67%',
    deltaPositive: true,
  },
  {
    id: 'agent-3',
    name: 'Application Agent',
    codename: 'WORKFLOW-EXEC-03',
    category: 'Workflow',
    status: 'approval_required',
    runtime: '01:30',
    tasksCount: 1345,
    successRate: 89.29,
    progressPercent: 45,
    model: 'GPT-4.5 Orion',
    lastAction: 'Awaiting human authorization for high-volume batch deployment',
    latencyMs: 310,
    tokensUsed: '2.1M',
    cost: '$8.45',
    chartData: [60, 65, 70, 68, 74, 80, 78, 85, 89.3],
    deltaRate: '-1.89%',
    deltaPositive: false,
  },
  {
    id: 'agent-4',
    name: 'QA Agent',
    codename: 'SENTINEL-EVAL-04',
    category: 'QA',
    status: 'idle',
    runtime: '00:00',
    tasksCount: 345,
    successRate: 99.4,
    progressPercent: 100,
    model: 'Claude 3.7 Haiku',
    lastAction: 'Standing by for next automated test suite dispatch',
    latencyMs: 88,
    tokensUsed: '850K',
    cost: '$1.25',
    chartData: [90, 92, 95, 96, 98, 99, 99.2, 99.4, 99.4],
    deltaRate: '+0.8%',
    deltaPositive: true,
  },
  {
    id: 'agent-5',
    name: 'Prompt Optimizer',
    codename: 'EVOLVER-GEN4',
    category: 'Optimizer',
    status: 'running',
    runtime: '04:12',
    tasksCount: 8420,
    successRate: 96.8,
    progressPercent: 88,
    model: 'DeepSeek R1 / Claude Hybrid',
    lastAction: 'Evaluating Gen-4 prompt mutations against test benchmark',
    latencyMs: 124,
    tokensUsed: '3.9M',
    cost: '$6.80',
    chartData: [50, 58, 64, 72, 80, 88, 92, 95, 96.8],
    deltaRate: '+12.4%',
    deltaPositive: true,
  },
];

export const mockRecentActivities: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'completed',
    title: 'Task completed',
    agent: 'Competitor Monitor',
    timestamp: '2m ago',
    details: 'Finished scraping 48 SaaS pricing tiers with DOM verification',
  },
  {
    id: 'act-2',
    type: 'improved',
    title: 'Agent improved',
    agent: 'Prompt Optimizer',
    timestamp: '8m ago',
    details: 'Mutant prompt Gen-4 achieved +14.2% accuracy on reasoning benchmark',
  },
  {
    id: 'act-3',
    type: 'started',
    title: 'Run started',
    agent: 'Lead Researcher',
    timestamp: '14m ago',
    details: 'Initiated 500 company profile synthesis pipeline',
  },
  {
    id: 'act-4',
    type: 'completed',
    title: 'Task completed',
    agent: 'QA Agent',
    timestamp: '22m ago',
    details: 'Completed regression test suite: 142/142 checks passed',
  },
];

export const mockAttentionItems: AttentionItem[] = [
  {
    id: 'att-1',
    type: 'approval',
    title: '3 approvals pending',
    agent: 'Application Agent',
    severity: 'high',
    time: '4m ago',
    actionLabel: 'Review Approvals',
  },
  {
    id: 'att-2',
    type: 'failure',
    title: '1 failed run',
    agent: 'DOM Parser Subsystem',
    severity: 'medium',
    time: '18m ago',
    actionLabel: 'Inspect Logs',
  },
  {
    id: 'att-3',
    type: 'approval',
    title: 'High-volume batch API call',
    agent: 'Synthesis Engine',
    severity: 'low',
    time: '32m ago',
    actionLabel: 'Authorize',
  },
];

export const mockNavLinks = [
  { id: 'overview', label: 'Overview', icon: 'Compass', active: true },
  { id: 'operations', label: 'Operations', icon: 'Activity', active: false },
  { id: 'agents', label: 'Agents', icon: 'Bot', active: false },
  { id: 'runs', label: 'Runs', icon: 'PlayCircle', active: false, badge: '12' },
  { id: 'approvals', label: 'Approvals', icon: 'CheckCircle2', active: false, badge: '3', badgeAlert: true },
  { id: 'evaluations', label: 'Evaluations', icon: 'Scale', active: false },
  { id: 'optimizer', label: 'Optimizer', icon: 'Zap', active: false },
  { id: 'analytics', label: 'Analytics', icon: 'BarChart3', active: false },
];
